import { useState } from "react";
import { Link } from "react-router-dom";
import {
  Search,
  BookOpen,
  Video,
  MapPin,
  FileSpreadsheet,
  ChevronDown,
  ChevronUp,
  MessageSquare,
  AlertTriangle,
  ArrowRight,
  Shield,
  HelpCircle,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

const GUIDES = [
  {
    icon: Video,
    title: "Live Streaming & Session Control",
    description: "Learn how to launch LiveKit video rooms, integrate YouTube embed URLs, and manage participant audio/video controls.",
    tags: ["Live Streaming", "LiveKit", "YouTube"],
  },
  {
    icon: MapPin,
    title: "GPS Geotagging & Location Pins",
    description: "Understand how Eventclick auto-captures latitude and longitude coordinates for rooms, attendance check-ins, and activity proof photos.",
    tags: ["Geotagging", "OpenStreetMap", "Coordinates"],
  },
  {
    icon: FileSpreadsheet,
    title: "Attendance Form Builder & Records",
    description: "Custom design attendance forms with required fields, datetime windows, and download verified PDF attendance reports.",
    tags: ["Form Builder", "PDF Reports", "Attendance"],
  },
  {
    icon: Shield,
    title: "Role & Permission Management",
    description: "Discover how NGO Admins assign Event Admins, manage Volunteers, and enforce strict tenant-isolated data controls.",
    tags: ["NGO Admin", "Event Admin", "Volunteers"],
  },
];

const FAQS = [
  {
    q: "How does GPS Geotagging work during attendance check-ins?",
    a: "When a participant submits an attendance form or uploads an activity proof photo, Eventclick requests browser location permissions. The GPS coordinates (latitude & longitude) are permanently attached to the attendance record and verified against the event room's pin location.",
  },
  {
    q: "When are PDF Reports available for download?",
    a: "PDF Reports can be generated by NGO Admins and Event Admins after an event room status transitions to 'Ended'. The PDF report includes verified attendee lists, geotag metadata, timestamps, and activity proof photo logs.",
  },
  {
    q: "Can I embed a YouTube Live stream instead of LiveKit?",
    a: "Yes! When creating or editing an event room, select 'YouTube' as your streaming provider and paste your YouTube Live embed URL or watch link. Viewers will be able to watch directly within Eventclick.",
  },
  {
    q: "What happens if a volunteer submits attendance outside the allowed time window?",
    a: "Event rooms specify an Attendance Window Before & After the scheduled start time. Submissions attempted outside this window are flagged as out-of-bounds, preventing unauthorized check-ins.",
  },
];

export const HelpCenter = () => {
  const [search, setSearch] = useState("");
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const filteredGuides = GUIDES.filter(
    (g) =>
      g.title.toLowerCase().includes(search.toLowerCase()) ||
      g.description.toLowerCase().includes(search.toLowerCase()) ||
      g.tags.some((t) => t.toLowerCase().includes(search.toLowerCase()))
  );

  return (
    <div className="max-w-5xl mx-auto space-y-8 animate-in fade-in">
      {/* Hero Search Header */}
      <div className="rounded-3xl bg-brand-gradient-tile p-8 text-white shadow-lg text-center space-y-4">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-white/15 backdrop-blur-md text-white border border-white/20">
          <HelpCircle className="w-3.5 h-3.5 text-purple-300" />
          Eventclick Documentation & Support
        </div>
        <h1 className="text-3xl font-bold font-display text-white tracking-tight">
          How can we help you today?
        </h1>
        <p className="text-sm text-white/80 max-w-xl mx-auto">
          Explore documentation guides, learn about GPS geotagging, live streaming, and find answers to common questions.
        </p>

        <div className="max-w-xl mx-auto relative pt-2">
          <Search className="w-5 h-5 text-gray-400 absolute left-4 top-1/2 -translate-y-1/2" />
          <Input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search guides, geotagging, streaming, reports..."
            className="pl-11 h-12 bg-white text-gray-900 placeholder:text-gray-400 rounded-2xl shadow-lg border-0 text-sm focus:ring-2 focus:ring-purple-500"
          />
        </div>
      </div>

      {/* Guide Cards Grid */}
      <div className="space-y-4">
        <h2 className="text-lg font-bold font-display text-gray-900 flex items-center gap-2">
          <BookOpen className="w-5 h-5 text-purple-600" />
          Popular Guides & Knowledge Base
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filteredGuides.map((guide, idx) => (
            <Card key={idx} className="card-static rounded-2xl hover:border-purple-200 hover:shadow-md transition-all">
              <CardContent className="p-5 space-y-3">
                <div className="w-10 h-10 rounded-xl bg-purple-50 border border-purple-100 flex items-center justify-center text-purple-700">
                  <guide.icon className="w-5 h-5" />
                </div>
                <h3 className="font-bold text-gray-900 font-display text-base">{guide.title}</h3>
                <p className="text-xs text-gray-500 leading-relaxed">{guide.description}</p>
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {guide.tags.map((tag) => (
                    <span key={tag} className="text-[10px] font-semibold bg-gray-100 text-gray-600 px-2 py-0.5 rounded-md">
                      #{tag}
                    </span>
                  ))}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* FAQs Section */}
      <div className="space-y-4">
        <h2 className="text-lg font-bold font-display text-gray-900">Frequently Asked Questions</h2>

        <div className="space-y-3">
          {FAQS.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <Card key={idx} className="card-static rounded-2xl overflow-hidden">
                <button
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  className="w-full p-4 text-left font-semibold text-sm text-gray-900 flex items-center justify-between gap-3 hover:bg-gray-50 transition-colors cursor-pointer"
                >
                  <span className="font-display">{faq.q}</span>
                  {isOpen ? (
                    <ChevronUp className="w-4 h-4 text-purple-600 shrink-0" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-gray-400 shrink-0" />
                  )}
                </button>
                {isOpen && (
                  <div className="px-4 pb-4 text-xs text-gray-600 leading-relaxed border-t border-gray-100 pt-3 bg-purple-50/30">
                    {faq.a}
                  </div>
                )}
              </Card>
            );
          })}
        </div>
      </div>

      {/* Support CTA Banner */}
      <Card className="rounded-3xl border-purple-100 bg-purple-50 p-6 flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="space-y-1 text-center md:text-left">
          <h3 className="font-bold text-purple-900 font-display text-base">Still need assistance?</h3>
          <p className="text-xs text-purple-700">Submit feedback or report an issue directly to our tech team.</p>
        </div>
        <div className="flex gap-3 shrink-0">
          <Link
            to="/feedback"
            className="inline-flex items-center gap-1.5 px-4 h-10 rounded-xl text-xs font-semibold bg-white border border-purple-200 text-purple-700 hover:bg-purple-100 transition-colors"
          >
            <MessageSquare className="w-4 h-4" />
            Send Feedback
          </Link>
          <Link
            to="/report-bug"
            className="inline-flex items-center gap-1.5 px-4 h-10 rounded-xl text-xs font-semibold bg-brand-gradient text-white shadow-xs hover:shadow-md transition-all"
          >
            <AlertTriangle className="w-4 h-4" />
            Report a Bug
          </Link>
        </div>
      </Card>
    </div>
  );
};
