#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# fetch-secrets.sh — Pull production secrets from AWS SSM Parameter Store
# ─────────────────────────────────────────────────────────────────────────────
#
# Prerequisites:
#   - AWS CLI installed: sudo apt-get install -y awscli
#   - EC2 instance must have IAM role with AmazonSSMReadOnlyAccess attached
#   - Secrets stored in SSM under /Eventclick/prod/*
#
# Usage (called by deploy.sh or manually):
#   ./scripts/fetch-secrets.sh              # writes to .env in project root
#   ./scripts/fetch-secrets.sh /tmp/.env    # writes to custom path
#
# How to populate SSM (one-time, run from your local machine with AWS credentials):
#   aws ssm put-parameter --name "/Eventclick/prod/JWT_SECRET"       --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/DB_PASSWORD"      --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/REDIS_PASSWORD"   --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/JWT_REFRESH_SECRET" --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/LIVEKIT_API_KEY"  --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/LIVEKIT_API_SECRET" --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/S3_ACCESS_KEY"    --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/S3_SECRET_KEY"    --value "..." --type SecureString --region ap-south-1
#   aws ssm put-parameter --name "/Eventclick/prod/RESEND_API_KEY"   --value "..." --type SecureString --region ap-south-1
#   # Add all other variables from .env.production.example similarly
#
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
SSM_PATH="/eventclick/prod"
AWS_REGION="${AWS_REGION:-ap-south-1}"
OUTPUT_FILE="${1:-.env}"

# ── Colors ────────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[SSM]${NC}  $(date +%H:%M:%S) $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $(date +%H:%M:%S) $1"; }
err()  { echo -e "${RED}[ERROR]${NC}$(date +%H:%M:%S) $1" >&2; }

# ── Check AWS CLI available ───────────────────────────────────────────────────
if ! command -v aws &>/dev/null; then
  err "AWS CLI not found. Install with: sudo apt-get install -y awscli"
  exit 1
fi

# ── Check IAM credentials are available (EC2 instance role or env vars) ──────
if ! aws sts get-caller-identity --region "$AWS_REGION" &>/dev/null; then
  err "AWS credentials not available. Ensure EC2 IAM role has AmazonSSMReadOnlyAccess."
  err "Or export AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN."
  exit 1
fi

log "Fetching secrets from SSM path: ${SSM_PATH} (region: ${AWS_REGION})"

# ── Fetch all parameters under /Eventclick/prod/ ───────────────────────────────
# --with-decryption: decrypt SecureString parameters
# --recursive: get all nested paths
PARAMS=$(aws ssm get-parameters-by-path \
  --path "$SSM_PATH" \
  --with-decryption \
  --recursive \
  --query "Parameters[*].{Name:Name,Value:Value}" \
  --output json \
  --region "$AWS_REGION" 2>/dev/null)

PARAM_COUNT=$(echo "$PARAMS" | python3 -c "import sys,json; data=json.load(sys.stdin); print(len(data))" 2>/dev/null || echo "0")

if [[ "$PARAM_COUNT" -eq 0 ]]; then
  err "No parameters found at SSM path '${SSM_PATH}'."
  err "Have you populated SSM? See the usage comments at the top of this script."
  exit 1
fi

log "Found ${PARAM_COUNT} parameters. Writing to ${OUTPUT_FILE}..."

# ── Write .env file ────────────────────────────────────────────────────────────
# Remove existing file first (security: don't append stale values)
rm -f "$OUTPUT_FILE"
touch "$OUTPUT_FILE"
chmod 600 "$OUTPUT_FILE"  # Owner read/write only — no group/other access

# Write header
cat >> "$OUTPUT_FILE" << EOF
# ─────────────────────────────────────────────────────────────────────────────
# AUTO-GENERATED by fetch-secrets.sh from AWS SSM Parameter Store
# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# SSM path: ${SSM_PATH}
# DO NOT COMMIT — this file is in .gitignore
# ─────────────────────────────────────────────────────────────────────────────
EOF

# Convert SSM JSON output to KEY=VALUE pairs
# SSM param name: /Eventclick/prod/JWT_SECRET → env key: JWT_SECRET
echo "$PARAMS" | python3 -c "
import sys, json
data = json.load(sys.stdin)
prefix = '${SSM_PATH}/'
for item in data:
    key = item['Name'].replace(prefix, '').replace('/', '_').upper()
    value = item['Value']
    # Escape any double quotes in value
    value = value.replace('\"', '\\\\\"')
    print(f'{key}=\"{value}\"')
" >> "$OUTPUT_FILE"

log "Secrets written to ${OUTPUT_FILE} (${PARAM_COUNT} variables, mode 600)"

# ── Verify required secrets are present ──────────────────────────────────────
REQUIRED_KEYS=(
  "JWT_SECRET"
  "JWT_REFRESH_SECRET"
  "DB_PASSWORD"
  "DATABASE_URL"
  "REDIS_PASSWORD"
  "LIVEKIT_API_KEY"
  "LIVEKIT_API_SECRET"
)

MISSING=()
for key in "${REQUIRED_KEYS[@]}"; do
  if ! grep -q "^${key}=" "$OUTPUT_FILE" 2>/dev/null; then
    MISSING+=("$key")
  fi
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
  warn "The following required secrets are MISSING from SSM:"
  for k in "${MISSING[@]}"; do
    warn "  - ${k}  →  aws ssm put-parameter --name '${SSM_PATH}/${k}' --value '...' --type SecureString --region ${AWS_REGION}"
  done
  err "Deployment may fail. Add missing secrets to SSM and retry."
  exit 1
fi

log "All required secrets present ✅"
