#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# update-cloudflare-ips.sh — regenerate nginx's trusted-proxy list
# ─────────────────────────────────────────────────────────────────────────────
# nginx restores the visitor's address from the CF-Connecting-IP header. That
# header is only trustworthy when the TCP peer really is Cloudflare: anyone who
# reaches the origin directly can set it to any value, and every IP-keyed rate
# limiter in the API would then see whatever address they chose.
#
# This script writes packages/client/cloudflare-realip.conf with one
# set_real_ip_from line per range Cloudflare publishes, so the header is
# honoured from those peers and ignored from everyone else.
#
# Usage (from the repo root):
#   scripts/update-cloudflare-ips.sh
#
# Commit the regenerated file. Cloudflare changes these ranges rarely; see
# docs/runbooks/origin-lockdown.md for when to rerun this and for the matching
# AWS security group change, which is the control Docker cannot bypass.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${SCRIPT_DIR}/../packages/client/cloudflare-realip.conf"

V4_URL="https://www.cloudflare.com/ips-v4"
V6_URL="https://www.cloudflare.com/ips-v6"

# Refuse to write a short list: a truncated download would silently stop
# trusting part of Cloudflare's edge and log those visitors as Cloudflare IPs.
MIN_V4=10
MIN_V6=5

fetch_ranges() {
  # Cloudflare omits the trailing newline; normalise and drop blank lines.
  curl -fsS --max-time 20 "$1" | tr -d '\r' | sed '/^[[:space:]]*$/d'
}

v4="$(fetch_ranges "$V4_URL")"
v6="$(fetch_ranges "$V6_URL")"

v4_count="$(printf '%s\n' "$v4" | wc -l | tr -d ' ')"
v6_count="$(printf '%s\n' "$v6" | wc -l | tr -d ' ')"

if [ "$v4_count" -lt "$MIN_V4" ] || [ "$v6_count" -lt "$MIN_V6" ]; then
  echo "Refusing to write: got ${v4_count} IPv4 and ${v6_count} IPv6 ranges (expected at least ${MIN_V4} and ${MIN_V6})." >&2
  exit 1
fi

# Every line must look like a CIDR before it goes anywhere near nginx.
if printf '%s\n%s\n' "$v4" "$v6" | grep -Ev '^[0-9a-fA-F:.]+/[0-9]{1,3}$' >/dev/null; then
  echo "Refusing to write: a downloaded line is not a CIDR range." >&2
  exit 1
fi

tmp="$(mktemp "${OUT}.XXXXXX")"
{
  echo "# Generated by scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%d). Do not edit by hand."
  echo "# Sources: ${V4_URL} and ${V6_URL}"
  echo "#"
  echo "# CF-Connecting-IP is honoured only when the TCP peer is one of these ranges."
  echo "# From any other peer, \$remote_addr stays the real peer address."
  echo ""
  echo "real_ip_header CF-Connecting-IP;"
  echo ""
  echo "# IPv4 (${v4_count})"
  printf '%s\n' "$v4" | sed 's/^/set_real_ip_from /; s/$/;/'
  echo ""
  echo "# IPv6 (${v6_count})"
  printf '%s\n' "$v6" | sed 's/^/set_real_ip_from /; s/$/;/'
} > "$tmp"
mv "$tmp" "$OUT"

echo "Wrote ${OUT}: ${v4_count} IPv4 + ${v6_count} IPv6 ranges."
